apps/payment/urls.py
from django.urls import path

from apps.payment.views import ChargeView

urlpatterns = [
    path('charge/', ChargeView.as_view(), name='charge'),
]

apps/user/urls.py
from django.urls import path

from apps.user.views import CustomLoginView, CustomLogoutView, SignUpView

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('signup/', SignUpView.as_view(), name='signup'),
]

thetask/urls.py
from django.contrib import admin
from django.urls import path, include

from apps.subscription.views import SubscriptionView

urlpatterns = [
    path('user/', include(('apps.user.urls', 'user'), namespace='user')),
    path('payment/', include(('apps.payment.urls', 'payment'), namespace='payment')),
    path('', SubscriptionView.as_view(), name='home'),
    path('admin/', admin.site.urls),

]

apps/payment/models.py
from django.utils.translation import gettext_lazy as _

from django.db import models
from django.conf import settings


class PaymentLog(models.Model):
    user = models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name=_('user'))
    data = models.JSONField()

    class Meta:
        verbose_name = _('payment log')
        verbose_name_plural = _('payment logs')

    def __str__(self):
        return f'{self.user}'

apps/subscription/models.py
from django.utils.translation import gettext_lazy as _
from django.db import models
from django.conf import settings


class Subscription(models.Model):
    is_active = models.BooleanField(default=True, verbose_name=_('is active'))
    subscriber = models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                                   related_name='subscriptions', verbose_name=_('subscriber'))
    start_date = models.DateTimeField(auto_created=True, verbose_name=_('start date'))
    end_date = models.DateTimeField(verbose_name=_('end date'))

    class Meta:
        verbose_name = _('subscription')
        verbose_name_plural = _('subscriptions')

    def __str__(self):
        return f'{self.subscriber}'

apps/user/models.py
from django.contrib.auth.models import AbstractUser as BaseUser


class User(BaseUser):
    pass

apps/user/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'fadeIn second'

apps/payment/views.py
from django.http import HttpResponseRedirect
from django.conf import settings
from django.views.generic import TemplateView

from apps.payment.models import PaymentLog
from apps.payment.stripe import get_token, get_payment_charge
from apps.subscription.views import start_subscription


class ChargeView(TemplateView):
    template_name = 'payment/charge.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['stripe_public_key'] = settings.STRIPE_PUBLISHABLE_KEY
        context['amount'] = 100
        context['currency'] = 'tl'
        return context

    def post(self, request):
        name = request.POST.get('name')
        card_number = request.POST.get('cardnumber')
        exp_month = int(request.POST.get('exp-date').split('/')[0])
        exp_year = int(request.POST.get('exp-date').split('/')[1])
        cvc = request.POST.get('cvc')
        card = {
            "name": name,
            "number": card_number,
            "exp_month": exp_month,
            "exp_year": exp_year,
            "cvc": cvc
        }
        token = get_token(card)
        charge = get_payment_charge(amount=100, currency="usd", description="test", token=token.stripe_id)
        if charge.paid:
            log_payment(user=request.user, data=charge)
            start_subscription(request.user)
        return HttpResponseRedirect('/')


def log_payment(user, data):
    PaymentLog.objects.create(user=user, data=data)

apps/subscription/views.py
from datetime import timedelta

from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView

from apps.subscription.book_api import get_adapter
from apps.subscription.models import Subscription
from apps.subscription.serializers import BookListSerializer


class SubscriptionView(TemplateView):
    template_name = 'home.html'

    @method_decorator(login_required(login_url=reverse_lazy('user:login')))
    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        try:
            subscription = Subscription.objects.get(subscriber=request.user, is_active=True)
            page = request.GET.get('page', 1)
            results = get_adapter().books(page)
            serializer = BookListSerializer(results, request)
            context['books'] = serializer.data
        except Subscription.DoesNotExist:
            subscription = None
        context['subscription'] = subscription
        return self.render_to_response(context)

    @method_decorator(login_required(login_url=reverse_lazy('user:login')))
    def post(self, request):
        try:
            subscription = Subscription.objects.get(subscriber=request.user, is_active=True)
            subscription.is_active = False
            subscription.save()
        except Subscription.DoesNotExist:
            print("user haven't any subscription")
        return HttpResponseRedirect(reverse_lazy('home'))


def start_subscription(subscriber):
    start_date = timezone.now()
    end_date = start_date + timedelta(days=30)
    Subscription.objects.create(
        subscriber=subscriber,
        start_date=start_date,
        end_date=end_date
    )

apps/user/views.py
from django.urls import reverse_lazy
from django.views import generic

from django.contrib.auth.views import LoginView, LogoutView

from apps.user.forms import CustomUserCreationForm


class CustomLoginView(LoginView):

    def get_success_url(self):
        return reverse_lazy('home')


class SignUpView(generic.CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('user:login')
    template_name = 'registration/signup.html'


class CustomLogoutView(LogoutView):
    next_page = reverse_lazy('user:login')

templates/base.html
{% load i18n static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}BASE{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    {% block extra_css %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url "home" %}">Thetask</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url "home" %}">{% trans "home"|title %} <span class="sr-only">(current)
                </span></a>
            </li>
            {% if subscription %}
                <li class="nav-item">
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">
                        <b>{% trans "subscription valid until"|title %}: </b> {{ subscription.end_date|date }}
                    </a>
                </li>
            {% endif %}
        </ul>
    </div>
    <div class="btn-group">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
                aria-expanded="false">
            {% trans "account"|title %}
        </button>
        <div class="dropdown-menu dropdown-menu-right">
            {% if request.user.is_authenticated %}
                {% if subscription %}
                    <form action="{% url "home" %}" method="post">
                        {% csrf_token %}
                        <button class="dropdown-item" type="submit">{% trans "unsubscribe"|title %}</button>
                    </form>
                    <div class="dropdown-divider"></div>
                {% endif %}
                <a class="dropdown-item" href="{% url "user:logout" %}">{% trans "logout"|title %}</a>
            {% else %}
                <button href="{% url "user:login" %}" class="dropdown-item"
                        type="button">{% trans "login"|title %}</button>
                <div class="dropdown-divider"></div>

                <button href="{% url "user:signup" %}" class="dropdown-item"
                        type="button">{% trans "signup"|title %}</button>
            {% endif %}
        </div>
    </div>
</nav>
<div class="content">
    {% block body %}{% endblock %}
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>
{% block extra_js %}{% endblock %}

</body>
</html>

templates/home.html
{% extends "base.html" %}{% load i18n static %}
{% block title %}{% trans "home"|title %}{% endblock %}
{% block body %}
    <div class="row">
        <div class="col-sm-12">
            {% if not subscription %}
                <br><br><br>
                <div class="text-center">
                    <h3>
                        {% trans "you have not any subscription, you should start your membership"|title %}</h3>
                    <a href="{% url "payment:charge" %}">{% trans "click for start"|title %}</a>
                </div>
            {% else %}
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">{% trans "image"|title %}</th>
                        <th scope="col">{% trans "title"|title %}</th>
                        <th scope="col">Isbn13</th>
                        <th scope="col">{% trans "price"|title %}</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for book in books %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td><img height="50" width="40" src="{{ book.image }}" alt=""></td>
                            <td>{{ book.title }}<br>
                                <small>{{ book.subtitle|truncatechars:50 }}</small>
                            </td>
                            <td>{{ book.isbn13 }}</td>
                            <td>{{ book.price }}</td>
                        </tr>
                    {% empty %}
                        <tr>
                            <th class="text-center" colspan="5" scope="row">{% trans "no result"|title %}</th>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% endif %}
        </div>
    </div>
{% endblock %}